#!/bin/bash

echo "Cleanup...";
rm -fr bower_components/
echo "Downloading..."
bower install bootstrap angular-route angular-sanitize
echo "Removing old files..."
rm -fr app/static/lib/*
echo "Creating dirs..."
mkdir -p app/static/lib/angularjs/plugins/angular-route/
mkdir app/static/lib/jquery/
mkdir app/static/lib/bootstrap/
mkdir app/static/lib/fonts/
mkdir app/static/lib/angularjs/plugins/angular-sanitize/
echo "Copying files into static/lib..."
# angular
cp bower_components/angular/angular.js app/static/lib/angularjs/
# angular-route
cp bower_components/angular-route/angular-route.js app/static/lib/angularjs/plugins/angular-route/
# bootstrap
cp bower_components/bootstrap/dist/css/bootstrap-theme.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/css/bootstrap.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/js/bootstrap.js app/static/lib/bootstrap/
cp -R bower_components/bootstrap/fonts/ app/static/lib/fonts/
# jquery
cp bower_components/jquery/dist/jquery.js app/static/lib/jquery/

echo "Removing bower_components/..."
rm -fr bower_components/
echo "done."
